name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all commits/branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs-material mike mkdocs-roamlinks-plugin

      - name: Deploy documentation
        env:
          VERSION_NAME: ${{ github.ref_name }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "scottTomaszewski@gmail.com"
          if [ "$VERSION_NAME" = "patron" ]; then
            mike deploy --push --update-aliases $VERSION_NAME latest
          else
            mike deploy --push $VERSION_NAME
          fi
